---
- hosts: centos_servers
  become: true
  tasks:

  - name: install apache and php
    package:
      name: 
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest
      update_cache: yes
    when: ansible_distribution == "CentOS" and ansible_distribution_version == "9"