- name: Download Apache Installer
  tags: apache
  ansible.windows.win_get_url:
    url: 'https://www.apachelounge.com/download/VS16/binaries/httpd-2.4.54-win32-VS16.zip'
    dest: 'C:\temp\httpd-2.4.54-win32-VS16.zip'

- name:  unzip apache
  tags: apache
  ansible.builtin.win_unzip:
    src: 'C:\temp\httpd-2.4.54-win32-VS16.zip'
    dest: 'C:\'

#- name: file exists
#  tags: test
#  ansible.windows.win_stat:
#    path: 'C:\Apache24\conf\httpd.conf'
#  register: result 
  
#- name: debug
#  tags: test
#  debug:
#    msg: "The contents of myvar: {{ result }}"
    
#- name: fetch config file
#  tags: test
#  ansible.builtin.fetch:
#    src: 'C:/Apache24/conf/httpd.conf'
#    dest: fetched/{{ inventory_hostname }}//httpd.conf
#    flat: true
#  when:
#    result.stat.exists
- name: update httpd.conf file
  tags: httpd_conf_update
  ansible.builtin.template:
    src: httpd.conf.j2
    dest: C:/temp/httpd.conf.updated
    backup: yes