---
- name: Install chocolatey
  tags: install_chocolatey
  win_chocolatey:
      name:
        - chocolatey
        - chocolatey-core.extension
      state: present

- name: Install python3
  tags: python3
  win_chocolatey:
    name: python3
    version: '3.10.6'
    package_params: "/InstallDir:C:\\temp\\python3"
    state: present

- name: Install other apps
  tags: apps
  win_chocolatey:
    name: '{{ item }}'
    state: present
    pinned: yes
    architecture: x86
    force: yes
  with_items:
  - 7zip
  - procexp
  - putty
  - windirstat
  - git
  - winscp
  - notepadplusplus.install